### ISSUE TITLE
Improving Website Performance - Optimizing Image Loading

### ISSUE THREAD

**Issue by sigi-campus02** [sigi-campus02/mindfulart.github.io#42]
## Problem
I've noticed that the images on my website are taking a significant amount of time to load, which is affecting the overall performance of the site. I ran a Lighthouse report, and the metrics for my gallery section are as follows:

- **First Contentful Paint**: 0.7 s
- **Largest Contentful Paint**: 2.2 s
- **Total Blocking Time**: 60 ms
- **Cumulative Layout Shift**: 0.004
- **Speed Index**: 0.8 s

The `Largest Contentful Paint` and `Speed Index` metrics are especially concerning, and I believe that optimizing image loading is essential to improve these numbers.

## Solution
I would like to address this issue by optimizing the way images are loaded on the website. Here are some potential solutions to consider:

1. **Image Compression**: Compress and optimize images to reduce their file size without compromising quality. This can significantly reduce loading times.

2. **Lazy Loading**: Implement lazy loading for images, ensuring that only the images in the viewport are loaded initially, improving page load speed.

3. **WebP Format**: Consider converting images to the WebP format, which generally offers better compression and faster loading times than traditional formats like JPEG and PNG.

4. **Content Delivery Network (CDN)**: Utilize a CDN to distribute images geographically closer to the user, reducing server latency and improving load times.

5. **Image Size and Dimensions**: Ensure that images are appropriately sized for their display on the website. Use responsive images to load different sizes based on the device's screen size.

6. **Image Caching**: Implement browser caching for images, allowing returning visitors to load images more quickly.

7. **Progressive Loading**: Consider implementing progressive image loading, where a low-resolution placeholder loads first, followed by the high-resolution image.

8. **Optimize Critical CSS**: Minimize and optimize the critical CSS for the website to improve rendering speed.

<img src="https://github.com/shcampus02/shcampus02.github.io/assets/147090809/3ef1f018-d2d8-4913-8d7b-a748201fa1fe" alt="Image 1" width="400">
<img src="https://github.com/shcampus02/shcampus02.github.io/assets/147090809/ce15f85c-d3d5-4ffc-b18c-231d4b090415" alt="Image 2" width="400">

**Comment by shcampus02** [comment]
![image](https://github.com/shcampus02/shcampus02.github.io/assets/147090809/6d1e4003-ddaa-44e9-91bd-b299bc512bb7)
![image](https://github.com/shcampus02/shcampus02.github.io/assets/147090809/1954896f-a8a0-43cc-a8ba-fcef71d3ef5a)
